version: '3'

services:
  ldap:
    image: osixia/openldap
    container_name: ldap_server_container
    environment:
      LDAP_ORGANISATION: "Mon Organisation"
      LDAP_DOMAIN: "mondomaine.local"
      LDAP_ADMIN_PASSWORD: "adminpassword"
    ports:
      - "389:389"
    volumes:
      - ./data/ldap_data:/var/lib/ldap
      - ./data/ldap_config:/etc/ldap/slapd.d
      - ./data/nouveauContenu.ldif:/nouveauContenu.ldif
    networks:
      - ldap_network

  ftp:
    build:
      context: .
      dockerfile_inline: |
          FROM stilliard/pure-ftpd
          
          COPY ./Configuration/FTP/pure-ftpd.conf /etc/pure-ftpd/pure-ftpd.conf
          COPY ./Configuration/FTP/pureftpd-ldap.conf /etc/pure-ftpd/pureftpd-ldap.conf

    container_name: ldap_ftp_container
    environment:
      LDAP_SERVER: "ldap://ldap"
      LDAP_BASE_DN: "dc=mondomaine,dc=local"
      LDAP_LOGIN_ATTRIBUTE: "uid"
      LDAP_BIND_DN: "cn=admin,dc=mondomaine,dc=local"
      LDAP_BIND_PW: "adminpassword"
    ports:
        - "21:21"
        - "30000-30009:30000-30009"
    volumes:
        - ./data/ftp_users:/home/ftpusers
        - ./Configuration/FTP/pure-ftpd.conf:/etc/pure-ftpd/pure-ftpd.conf
        - ./Configuration/FTP/pureftpd-ldap.conf:/etc/pure-ftpd/pureftpd-ldap.conf

    networks:
        - ldap_network
    depends_on:
      - ldap

  phpldapadmin:
    image: osixia/phpldapadmin
    container_name: ldap_phpldapadmin_container
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: 0
    ports:
      - "6443:80"
    depends_on:
      - ldap
    networks:
      - ldap_network

  web:
    build:
      context: .
      dockerfile_inline: |
        FROM php:apache
        RUN apt-get update && apt-get install -y libldap2-dev && \
          docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && \
          docker-php-ext-install ldap
    container_name: ldap_web_portal_container
    volumes:
      - ./../app:/var/www/html
    ports:
      - "8080:80"
    networks:
      - ldap_network
networks:
  ldap_network:
    driver: bridge